# Generated by Django 3.0.8 on 2021-05-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=100)),
                ('bount', models.IntegerField(max_length=13)),
            ],
        ),
    ]
